# isntall libs

In [2]:
# Install libs
%pip install numpy matplotlib keras tensorflow pydot
%pip install -qq keras-cv
%pip install -qq wandb
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


# imports

In [3]:
%matplotlib inline

import os
from os.path import join
import numpy as np
import keras
from keras import layers
from tensorflow import data as tf_data
import matplotlib.pyplot as plt
import struct
import random
from array import array
from IPython.display import display, Markdown
import triangle_gen
from sklearn.model_selection import train_test_split

# model

In [14]:
dataset_size = 10000
triangles = []

x_data_set = []
y_data_set = []



for n in range(dataset_size):
    #2 angles and 1 sides known
    triangle = triangle_gen.TriangleGenerator().generate_random_triangle_via_angles(known_indices=[0,2,4])
    x = (triangle.angles[0], triangle.angles[2], triangle.sides[0], triangle.triangle_type)
    y = (triangle.sides[2], triangle.sides[0], triangle.angles[1])
    x_data_set.append(x)
    y_data_set.append(y)
    
x_data_set = np.array(x_data_set)
y_data_set = np.array(y_data_set)
    
print(x_data_set)
print(y_data_set)
X_train, X_test, y_train, y_test = train_test_split(x_data_set, y_data_set, test_size=0.2, random_state=42)


model_1 = keras.Sequential([
    keras.layers.Flatten(input_shape=[4]),        # In layer
    keras.layers.Dense(128, activation=keras.activations.relu),        # Hidden layer
    keras.layers.Dense(128, activation=keras.activations.linear),        # Hidden layer
    keras.layers.Dense(128, activation=keras.activations.relu),        # Hidden layer
    keras.layers.Dense(3, activation='linear')       # Out layer
])

model_1.compile(optimizer='adam', loss='mean_squared_error')

model_1.fit(X_train, y_train, epochs=50, batch_size=8)

score = model_1.evaluate(X_test, y_test, verbose=0)
print("Accuracy:", score)

display(Markdown(f"Accuracy: {score}<br>"))

[[ 3.          2.65045182 13.         42.        ]
 [ 4.          1.1040625  77.         42.        ]
 [ 1.          0.82192564 58.         42.        ]
 ...
 [ 7.         17.18656743 63.         42.        ]
 [ 9.         12.71749805 29.         42.        ]
 [ 2.          5.31861807 63.         42.        ]]
[[112.          13.           0.72785258]
 [ 87.          77.           3.90282895]
 [ 71.          58.           0.89691321]
 ...
 [ 24.          63.          15.33435892]
 [ 42.          29.           6.52082948]
 [ 22.          63.           4.75702532]]
Epoch 1/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 399.5044
Epoch 2/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 97.9686
Epoch 3/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 62.8264
Epoch 4/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 55.4683
Epoch 5/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 38.6817
Epoch 6/50
1000/1000 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 34.5670
Epoch 7/5

Accuracy: 7.102090358734131<br>